WebProgramlamaOdev/WebProgramlamaOdev/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebProgramlamaOdev.Controllers
{
    public class RolController : Controller
    {
        // GET: Rol
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebProgramlamaOdev/WebProgramlamaOdev/Controllers/RolYonetimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebProgramlamaOdev.Controllers
{
    public class RolYonetimController : Controller
    {
        // GET: RolYonetim
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebProgramlamaOdev/WebProgramlamaOdev/Views/Rol/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}
<div class="row" style="text-align:center;">
    <h2>@Resources.Language.Roller</h2>
    <hr />
</div>
@Html.ActionLink(Resources.Language.RolEkle, "RolEkle") | @Html.ActionLink(Resources.Language.RolAta, "RolKullaniciEkle")
<br />
<br />
@foreach (var item in Model)
{

    <tr>
        <td>@item.Name : </td>
        <td> @item.Users.Count</td>
    </tr>

    <br />        <br />
}

WebProgramlamaOdev/WebProgramlamaOdev/Views/Rol/RolEkle.cshtml
@model WebProgramlamaOdev.Models.Roller
@{
    ViewBag.Title = "RolEkle";
}

<div class="row" style="text-align:center;">
    <h2>@Resources.Language.RolEkle</h2>
    <hr />
</div>
@using (Html.BeginForm("RolEkle", "RolYonetim", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Rol Adı : ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <br /><br />
    <input type="submit" value="@Resources.Language.Ekle" style="margin-left:100px;" />
}
<br /><br />

WebProgramlamaOdev/WebProgramlamaOdev/Views/Rol/RolKullaniciEkle.cshtml
@model WebProgramlamaOdev.Models.RolEkleModel

@{
    ViewBag.Title = "RolKullaniciEkle";
}

<div class="row" style="text-align:center;">
    <h2>@Resources.Language.RolAta</h2>
    <hr />
</div>

@using (Html.BeginForm("RolKullaniciEkle", "Rol", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kullanıcı Adı : ", htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.TextBoxFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <br />    <br />
    <div class="form-group">
        @Html.Label("Rol Adı : ", htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.TextBoxFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
}